name: 'Linters'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  clj-kondo:
    name: runner / clj-kondo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yisraeldov/reviewdog-cljkondo-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review

